# Generated by Django 2.2.6 on 2020-11-02 15:33

from decimal import Decimal
from django.db import migrations, models
import videos.models
import videos.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=videos.storage.PublicMediaStorage(progress_percentage_class=videos.models.ProgressPercentage), upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProcessingMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_name', models.TextField(unique=True)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('uploading', 'Uploading'), ('done', 'Done')], default='initial', max_length=10)),
                ('upload_progress_percents', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3)),
            ],
        ),
    ]
