# Generated by Django 3.1.3 on 2020-11-02 20:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprocessingmonitor',
            name='status',
            field=models.CharField(choices=[('initial', 'Start'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('done', 'Done')], default='initial', max_length=10),
        ),
        migrations.AlterField(
            model_name='videoprocessingmonitor',
            name='upload_progress_percents',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4),
        ),
    ]
