# Generated by Django 3.1.3 on 2020-11-06 10:44

from django.db import migrations, models
import videos.storage


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_temporaryvideofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryvideofile',
            name='video_name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporaryvideofile',
            name='video',
            field=models.FileField(storage=videos.storage.OverwriteStorage, upload_to='temp/videos/'),
        ),
    ]
