# Generated by Django 3.1.3 on 2020-11-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20201116_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocessingmonitor',
            name='has_slices',
            field=models.BooleanField(default=False),
        ),
    ]
