# Generated by Django 3.1.3 on 2020-12-03 11:31

from django.db import migrations
import json


def update_events_structure(apps, schema_editor):
    VPM = apps.get_model('videos', 'VideoProcessingMonitor')
    for vpm in VPM.objects.all():
        if not vpm.events:
            continue

        events = json.loads(vpm.events)

        if not events:
            continue

        new_events = {}
        for slice_name, slice_events in events.items():
            new_events[slice_name] = {
                'status': 'pending',
                'events': slice_events
            }
        vpm.events = json.dumps(new_events)
        vpm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_videoprocessingmonitor_events'),
    ]

    operations = [
        migrations.RunPython(update_events_structure)
    ]
