# Generated by Django 3.2.4 on 2021-07-08 18:12

from django.db import migrations, models
import videos.storage


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20201203_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryvideofile',
            name='video',
            field=models.FileField(storage=videos.storage.OverwriteStorage(), upload_to='temp/videos/'),
        ),
    ]
