# Generated by Django 3.2.4 on 2021-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_usersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='settings',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
